### ISSUE TITLE
Tarea de Síntesis

### ISSUE THREAD

**Issue by JeserLeonel** [SistemasTecTlaxiaco/sintesis-JeserLeonel#2]
[Los elementos importantes de la gestión de proyectos de software. .pdf](https://github.com/SistemasTecTlaxiaco/sintesis-JeserLeonel/files/7151423/Los.elementos.importantes.de.la.gestion.de.proyectos.de.software.pdf)

**Comment by Eva155** [comment]
Calificación: 20 PUNTOS 
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
